---
title: "Data Wrangling"
author: "Emma Kaufman and Jenn McNeill"
date: "2024-03-19"
output: pdf_document
---
```{r}
library(forecast)
library(tseries)
library(ggplot2)
library(Kendall)
library(lubridate)
library(tidyverse)
library(ggthemes)
library(sarima)
library(dplyr)
library(cowplot)
library(readxl)
library(readr)
library(corrplot)
library(dplyr)
library(outliers)

```

```{r, read in the data}
#uploading data and converting dates to date format
Aquifer_Auser <- read_csv("Data/Raw/Aquifer_Auser.csv")
Aquifer_Auser$Date <- dmy(Aquifer_Auser$Date)

Aquifer_Doganella <- read_csv("Data/Raw/Aquifer_Doganella.csv")
Aquifer_Doganella$Date <- dmy(Aquifer_Doganella$Date)

Aquifer_Luco <- read_csv("Data/Raw/Aquifer_Luco.csv")
Aquifer_Luco$Date <- dmy(Aquifer_Luco$Date)

Aquifer_Petrignano <- read_csv("Data/Raw/Aquifer_Petrignano.csv")
Aquifer_Luco$Date <- dmy(Aquifer_Luco$Date)

Aquifer_Auser_Long <- pivot_longer(Aquifer_Auser, Depth_to_Groundwater_LT2:Depth_to_Groundwater_DIEC, names_to="GW Well", values_to= "Depth")


#looking at initial correlation of groundwater wells
Auser.subset <- 
  Aquifer_Auser %>% 
  select(Depth_to_Groundwater_LT2:Depth_to_Groundwater_DIEC) %>% 
  na.omit()

#how correlated are the different groundwater wells within one aquifer?
AuserCorr <- cor(Auser.subset)
corrplot(AuserCorr, method = "ellipse")
corrplot.mixed(AuserCorr, upper = "ellipse")
 
```
```{r}
#making time series objects cleaned for CoS and DIEC

#remote NAs from the dataframe
CoS_df <- auser_nas %>%
  slice(3614:8154) %>%
  select(Date, Depth_to_Groundwater_CoS)

DIEC_df <- auser_nas %>% 
  slice(4687:8154) %>% 
  select(Date, Depth_to_Groundwater_DIEC)

CoS_ts <- ts(CoS_df$Depth_to_Groundwater_CoS, start = c(2008,01,25), frequency= 365)
autoplot(CoS_ts)
CoS_ts_clean <- tsclean(CoS_ts)
autoplot(CoS_ts_clean)
  
  
  
DIEC_ts <- ts(DIEC_df$Depth_to_Groundwater_DIEC, start = c(2011,01,02), frequency= 365)
autoplot(DIEC_ts)
DIEC_ts_clean <- tsclean(DIEC_ts)

autoplot(DIEC_ts_clean) +
  autolayer(DIEC_ts, color= "blue")

autoplot(CoS_ts_clean) +
  autolayer(CoS_ts, color= "lightgreen")

```
 
making a df for rainfall and date

```{r}
#rainfall data
rainfall_auser <- auser_raw %>% 
  slice(2860:8154) %>% 
  select(Date:Rainfall_Fabbriche_di_Vallico)

# Find the indices of NA values
na_indices_rainfall <- which(is.na(rainfall_auser), arr.ind = TRUE)

# Print the row and column indices of NA values
print(na_indices_rainfall)
```

making a df for temp and date
```{r}
#temperature data
temperature_auser <- auser_raw %>% 
  select(Date,Temperature_Orentano:Temperature_Lucca_Orto_Botanico)

#note: 0 is essentially NA for the beginning rows, true zero is 0.0
```

making a df for volume and date 
```{r}
#volume of water going to use 
volume_auser <- auser_raw %>% 
  slice(2495:8154) %>% 
  select(Date,Volume_POL:Volume_CSAL)

```

make objects that are start date for each well 
```{r}
start_LT2 <- as.Date("2006-01-01")
start_SAL <- as.Date("2007-04-06")
start_PAG <- as.Date("2009-01-01")
start_CoS <- as.Date("2008-01-25")
start_DIEC <- as.Date("2011-01-02")
```

